/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmepubextractor_free: (a: number, b: number) => void;
export const wasmepubextractor_get_chapter: (a: number, b: number) => any;
export const wasmepubextractor_get_chapter_count: (a: number) => any;
export const wasmepubextractor_get_chapter_json: (a: number, b: number) => any;
export const wasmepubextractor_get_chapter_resource: (a: number, b: number, c: number, d: number) => any;
export const wasmepubextractor_get_chapter_text: (a: number, b: number) => any;
export const wasmepubextractor_get_chapters_text: (a: number) => any;
export const wasmepubextractor_get_chapters_text_json: (a: number) => any;
export const wasmepubextractor_get_cover_image: (a: number) => any;
export const wasmepubextractor_get_cover_image_format: (a: number) => any;
export const wasmepubextractor_get_cover_image_len: (a: number) => any;
export const wasmepubextractor_get_metadata: (a: number) => any;
export const wasmepubextractor_get_metadata_is_valid: (a: number) => any;
export const wasmepubextractor_get_metadata_json: (a: number) => any;
export const wasmepubextractor_get_resource: (a: number, b: number, c: number) => any;
export const wasmepubextractor_get_title: (a: number) => any;
export const wasmepubextractor_get_toc: (a: number) => any;
export const wasmepubextractor_get_toc_json: (a: number) => any;
export const wasmepubextractor_get_total_char_count: (a: number) => any;
export const wasmepubextractor_get_total_word_count: (a: number) => any;
export const wasmepubextractor_has_cover: (a: number) => any;
export const wasmepubextractor_load_from_bytes: (a: number, b: any) => any;
export const wasmepubextractor_new: () => number;
export const wasmepubextractor_resolve_chapter_resource_path: (a: number, b: number, c: number, d: number) => any;
export const wasm_bindgen_9a13aa7088a40b79___convert__closures_____invoke___wasm_bindgen_9a13aa7088a40b79___JsValue__core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_9a13aa7088a40b79___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_9a13aa7088a40b79___convert__closures_____invoke___js_sys_11831930ac79a498___Function_fn_wasm_bindgen_9a13aa7088a40b79___JsValue_____wasm_bindgen_9a13aa7088a40b79___sys__Undefined___js_sys_11831930ac79a498___Function_fn_wasm_bindgen_9a13aa7088a40b79___JsValue_____wasm_bindgen_9a13aa7088a40b79___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
